name: pod-security-standards-test
policies:
  - ../../policies/pod-security-standards.yaml
resources:
  - resources.yaml
results:
  - policy: pod-security-standards
    rule: disallow-privilege-escalation
    resource: pss-pod-valid
    kind: Pod
    result: pass
  - policy: pod-security-standards
    rule: require-readonly-rootfs
    resource: pss-pod-valid
    kind: Pod
    result: pass
  - policy: pod-security-standards
    rule: require-drop-all-capabilities
    resource: pss-pod-valid
    kind: Pod
    result: pass
  - policy: pod-security-standards
    rule: disallow-privilege-escalation
    resource: pss-pod-invalid-escalation
    kind: Pod
    result: fail
  - policy: pod-security-standards
    rule: disallow-privileged-containers
    resource: pss-pod-invalid-privileged
    kind: Pod
    result: fail
