apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: pokedex-secret-store
  labels:
    app.kubernetes.io/name: pokedex
    app.kubernetes.io/part-of: pokedex-platform
    app.kubernetes.io/component: secrets-management
spec:
  provider:
    # --------------------------------------------------------------------------
    # Opción A: HashiCorp Vault On-Premise / Proxmox
    # --------------------------------------------------------------------------
    vault:
      server: "https://vault.internal.pokedex.net:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "pokedex-app-role"
          serviceAccountRef:
            name: pokedex-vault-auth-sa
            namespace: kube-system
    # --------------------------------------------------------------------------
    # Opción B (Comentada): AWS Secrets Manager para Clústeres EKS
    # --------------------------------------------------------------------------
    # aws:
    #   service: SecretsManager
    #   region: us-east-1
    #   auth:
    #     jwt:
    #       serviceAccountRef:
    #         name: pokedex-irsa-sa
    #         namespace: pokedex
