{{- if and .Values.externalSecrets .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pokedex.fullname" . }}-external-secrets
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | default "vault-backend" }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ include "pokedex.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: POSTGRES_PASSWORD
    - secretKey: ADMIN_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: ADMIN_API_KEY
    - secretKey: ADMIN_SESSION_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: ADMIN_SESSION_SECRET
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: REDIS_PASSWORD
    - secretKey: REDIS_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: REDIS_URL
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: DATABASE_URL
    - secretKey: AI_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: AI_API_KEY
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "pokedex/production" }}
        property: GEMINI_API_KEY
{{- end }}
