{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
    app: pgbouncer
spec:
  ports:
    - port: 6432
      targetPort: 6432
      name: pgbouncer
  selector:
    app: pgbouncer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
    app: pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicaCount }}
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
        {{- include "pokedex.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: pgbouncer
          image: "{{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}"
          imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
          ports:
            - containerPort: 6432
              name: pgbouncer
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: pokemon-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pokemon-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pokemon-config
                  key: POSTGRES_DB
            - name: POOL_MODE
              value: {{ .Values.pgbouncer.poolMode | quote }}
            - name: MAX_CLIENT_CONN
              value: {{ .Values.pgbouncer.maxClientConn | quote }}
            - name: DEFAULT_POOL_SIZE
              value: {{ .Values.pgbouncer.defaultPoolSize | quote }}
          resources:
            {{- toYaml .Values.pgbouncer.resources | nindent 12 }}
{{- end }}
