{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pokemon-redis-svc
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
    app: redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.port }}
      name: redis
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
    app: redis
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.port }}
      name: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        {{- include "pokedex.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}
