{{- if and .Values.externalSecrets .Values.externalSecrets.enabled .Values.externalSecrets.secretStore .Values.externalSecrets.secretStore.create }}
apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
metadata:
  name: {{ .Values.externalSecrets.secretStore.name | default (printf "%s-secretstore" (include "pokedex.fullname" .)) }}
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
  {{- with .Values.externalSecrets.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- toYaml .Values.externalSecrets.secretStore.provider | nindent 4 }}
{{- end }}
