{{- if and (not .Values.secrets.existingSecret) (not (and .Values.externalSecrets .Values.externalSecrets.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pokedex.secretName" . }}
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "Se requiere definir una contraseña segura para .Values.postgresql.auth.password" .Values.postgresql.auth.password | quote }}
  ADMIN_API_KEY: {{ required "Se requiere definir una clave segura para .Values.secrets.adminApiKey" .Values.secrets.adminApiKey | quote }}
  ADMIN_SESSION_SECRET: {{ required "Se requiere definir un secreto criptográfico seguro e independiente para .Values.secrets.adminSessionSecret" .Values.secrets.adminSessionSecret | quote }}
  AI_API_KEY: {{ .Values.secrets.aiApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword | quote }}
  REDIS_PASSWORD: {{ required "Se requiere definir una contraseña segura para .Values.redis.auth.password" .Values.redis.auth.password | quote }}
  REDIS_URL: {{ printf "redis://:%s@pokemon-redis-svc:%v" (required "Se requiere definir una contraseña segura para .Values.redis.auth.password" .Values.redis.auth.password) .Values.redis.port | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.postgresql.auth.username (required "Se requiere definir una contraseña segura para .Values.postgresql.auth.password" .Values.postgresql.auth.password) (ternary "pgbouncer-service" "postgres-service" .Values.pgbouncer.enabled) (ternary 6432 .Values.postgresql.port .Values.pgbouncer.enabled) .Values.postgresql.auth.database | quote }}
{{- end }}
