apiVersion: v1
kind: Secret
metadata:
  name: pokemon-secrets
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  ADMIN_API_KEY: {{ required "Se requiere definir una clave segura para .Values.secrets.adminApiKey" .Values.secrets.adminApiKey | quote }}
  AI_API_KEY: {{ .Values.secrets.aiApiKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minioRootPassword | quote }}
