---
# ==============================================================================
# Inventario Lab (Entorno de Laboratorio y Pre-producción Efímero)
# ==============================================================================
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_name: pokedex
    mgmt_cidr: "10.0.0.0/16"
    k8s_cluster_cidr: "10.244.0.0/16"
  children:
    k8s_control_plane:
      hosts:
        lab-k8s-master-01:
          ansible_host: 10.0.10.10
          node_role: control-plane
    k8s_workers:
      hosts:
        lab-k8s-worker-01:
          ansible_host: 10.0.10.11
          node_role: worker
    k8s_cluster:
      children:
        k8s_control_plane:
        k8s_workers:
    standalone_servers:
      hosts:
        lab-node-01:
          ansible_host: 10.0.10.20
          env: lab
