# ==============================================================================
# Sobrescritura de Values para Entorno On-Premise (Proxmox VE / K8s Interno)
# ==============================================================================

global:
  environment: onprem-proxmox
  namespace: pokemon-app

api:
  replicaCount: 2
  deploymentAnnotations:
    reloader.stakater.com/auto: "true"
  image:
    repository: ghcr.io/rocapellino/pokedex-api
    digest: "sha256:4113ac3d61577bd4eef013e80ec8f05ffcfa4c079b51a1dcec9d884dacc4ddbd" # SHA256 digest pinning inmutable (SSOT)
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  autoscaling:
    enabled: false  # En Proxmox mantenemos capacidad fija garantizada

web:
  replicaCount: 2
  image:
    repository: ghcr.io/rocapellino/pokedex-web
    digest: "sha256:9cc9468cb10ed865e8182e4a2cf4fc0d0196d6fa6f88ac4cf921a70ca92b1b1c" # SHA256 digest pinning inmutable (SSOT)
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "64Mi"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "internal-ca-issuer"
  hosts:
    - host: pokedex.proxmox.internal.lan
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: pokemon-api-svc
              port:
                number: 3000
        - path: /pokemons
          pathType: Prefix
          backend:
            service:
              name: pokemon-api-svc
              port:
                number: 3000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pokemon-web-svc
              port:
                number: 8080
  tls:
    - secretName: pokedex-internal-tls
      hosts:
        - pokedex.proxmox.internal.lan

secrets:
  existingSecret: "pokemon-secrets"

externalSecrets:
  enabled: true
  refreshInterval: "1h"
  targetSecretName: "pokemon-secrets"
  secretStoreRef:
    name: "vault-backend"
    kind: "ClusterSecretStore"
  remoteRef:
    key: "secret/data/pokedex/production"
