# ==============================================================================
# Plantilla de Configuración para Contenedores LXC en Proxmox VE
# (/etc/pve/lxc/<vmid>.conf)
# ==============================================================================
# Habilita ejecución segura de Docker sin necesidad de VMs pesadas (Nesting & Keyctl)
# ==============================================================================

arch: amd64
cores: 2
features: nesting=1,keyctl=1
hostname: pokedex-prod
memory: 4096
# NOTA: Omitir 'hwaddr' para que Proxmox VE genere una MAC única automáticamente y evitar colisiones ARP/DHCP
net0: name=eth0,bridge=vmbr0,firewall=1,ip=dhcp,type=veth
ostype: ubuntu
rootfs: local-lvm:subvol-200-disk-0,size=20G
swap: 1024
unprivileged: 1
