# ==============================================================================
# Inventario de Servidores y Nodos - Pokédex DevOps
# ==============================================================================

[k8s_control_plane]
k8s-master-01 ansible_host=192.168.1.10 node_role=control-plane

[k8s_workers]
k8s-worker-01 ansible_host=192.168.1.11 node_role=worker
k8s-worker-02 ansible_host=192.168.1.12 node_role=worker

[k8s_cluster:children]
k8s_control_plane
k8s_workers

[standalone_servers]
pokedex-prod-01 ansible_host=192.168.1.20 env=production
pokedex-staging-01 ansible_host=192.168.1.21 env=staging

[all:vars]
ansible_python_interpreter=/usr/bin/python3
app_name=pokedex
docker_compose_version=v2.24.5
