apiVersion: v1
kind: ConfigMap
metadata:
  name: pokemon-config
  namespace: pokemon-app
data:
  PORT: "3000"
  ENVIRONMENT: "production"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pokedex_db"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://redis-service:6379/0"
