apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: pokemon-app
data:
  pgbouncer.ini: |
    [databases]
    pokedex_db = host=postgres-service port=5432 auth_user=postgres dbname=pokedex_db

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 20
    min_pool_size = 5
    reserve_pool_size = 5
    reserve_pool_timeout = 5
    max_db_connections = 50
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: pokemon-app
  labels:
    app: pgbouncer
spec:
  ports:
    - port: 6432
      targetPort: 6432
      name: pgbouncer
  selector:
    app: pgbouncer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: pokemon-app
  labels:
    app: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:1.23.1
          ports:
            - containerPort: 6432
              name: pgbouncer
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pokemon-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pokemon-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "pokedex_db"
            - name: POOL_MODE
              value: "transaction"
            - name: MAX_CLIENT_CONN
              value: "500"
            - name: DEFAULT_POOL_SIZE
              value: "20"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
