apiVersion: batch/v1
kind: Job
metadata:
  name: pokemon-db-seed-job
  namespace: pokemon-app
  labels:
    app: pokemon-db-seed
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: pokemon-db-seed
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-seeder
          image: pokemon-api:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "apps/api/scripts/bulk_load_pokemons.py"]
          envFrom:
            - configMapRef:
                name: pokemon-config
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
