# ==============================================================================
# Sobrescritura de Values para Entorno de Nube Pública (AWS / GCP / Azure)
# ==============================================================================

global:
  environment: public-cloud
  namespace: pokemon-app

api:
  replicaCount: 3
  deploymentAnnotations:
    reloader.stakater.com/auto: "true"
  image:
    repository: ghcr.io/rocapellino/pokedex-api
    digest: "sha256:4113ac3d61577bd4eef013e80ec8f05ffcfa4c079b51a1dcec9d884dacc4ddbd" # SHA256 digest pinning inmutable (SSOT)
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1500m"
      memory: "2Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

web:
  replicaCount: 3
  image:
    repository: ghcr.io/rocapellino/pokedex-web
    digest: "sha256:9cc9468cb10ed865e8182e4a2cf4fc0d0196d6fa6f88ac4cf921a70ca92b1b1c" # SHA256 digest pinning inmutable (SSOT)
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6

ingress:
  enabled: true
  className: "alb" # o gce / traefik según el proveedor de nube
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
  hosts:
    - host: pokedex.cloud.rodrigo.dev
      paths:
        - path: /api/
          pathType: Prefix
          backend:
            service:
              name: pokemon-api-svc
              port:
                number: 3000
        - path: /pokemons
          pathType: Prefix
          backend:
            service:
              name: pokemon-api-svc
              port:
                number: 3000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pokemon-web-svc
              port:
                number: 8080
  tls:
    - secretName: pokedex-cloud-cert
      hosts:
        - pokedex.cloud.rodrigo.dev

secrets:
  existingSecret: "pokemon-secrets"

externalSecrets:
  enabled: true
  refreshInterval: "1h"
  targetSecretName: "pokemon-secrets"
  secretStoreRef:
    name: "aws-secrets-manager"
    kind: "ClusterSecretStore"
  remoteRef:
    key: "pokedex/production"
