name: require-seccomp-profile-test
policies:
  - ../../policies/require-seccomp-profile.yaml
resources:
  - resources.yaml
results:
  - policy: require-seccomp-profile
    rule: check-seccomp-profile
    resource: seccomp-pod-valid
    kind: Pod
    result: pass
  - policy: require-seccomp-profile
    rule: check-seccomp-profile
    resource: seccomp-pod-invalid
    kind: Pod
    result: fail
