---
# ==============================================================================
# Playbook: Preparación de Nodos para Kubernetes y Docker Engine
# ==============================================================================
- name: Aprovisionamiento y Configuración Base de Nodos
  hosts: all
  become: true
  roles:
    - role: ../roles/base_os
    - role: ../roles/kubernetes_prerequisites
    - role: ../roles/container_runtime
